### ISSUE TITLE
Clarification on Ignite cache xml configuration

### ISSUE THREAD

**Issue by Danny-Hazelcast** [apacheignite/yardstick-ignite#3]
I have this cache xml configuration

```
<bean class="org.apache.ignite.configuration.CacheConfiguration">
<property name="name" value="atomic"/>
<property name="cacheMode" value="PARTITIONED"/>
<property name="atomicityMode" value="ATOMIC"/>
<property name="swapEnabled" value="false"/>
</bean>
```

my question is.

1  what number of backups will the "atomic"  cache have ? 

2  what CacheWriteSynchronizationMode mode will be used,  if there are backups, configured by default      when using the above xml cache configuration 

Thanks

**Comment by Danny-Hazelcast** [comment]
hear we can see http://apacheignite.gridgain.org/v1.1/docs/primary-and-backup-copies

   "  By default, backups are turned off for better performance.  "

however I note the version is v1.1  so I am still not 100% clear

Thanks

**Comment by ntikhonov** [comment]
Hello!
Yes, by default backups are turned off.
https://apacheignite.readme.io/docs/primary-and-backup-copies

**Comment by Danny-Hazelcast** [comment]
@ntikhonov  so 

```
<bean class="org.apache.ignite.configuration.CacheConfiguration">
<property name="name" value="atomic"/>
<property name="cacheMode" value="PARTITIONED"/>
<property name="atomicityMode" value="ATOMIC"/>
<property name="swapEnabled" value="false"/>
</bean>
```

and 

```
<bean class="org.apache.ignite.configuration.CacheConfiguration">
<property name="name" value="atomic"/>
<property name="cacheMode" value="PARTITIONED"/>
<property name="atomicityMode" value="ATOMIC"/>
<property name="swapEnabled" value="false"/>

<property name="backups" value="0"/>
</bean>
```

are equal, so will both give a cache configured in the same way  ?

Thanks,

**Comment by yzhdanov** [comment]
Danny, that's correct. You can check out the default values for config parameters here - https://ignite.apache.org/releases/1.5.0.final/javadoc/org/apache/ignite/configuration/CacheConfiguration.html

Thanks!
